version: '3.8'
services:
  blog:
    build: .
    command: /bin/bash -c "/script.sh database:3306 -- python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      - DEBUG=1

  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3309:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
