# Generated by Django 4.2 on 2024-04-01 19:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('author', 'blog')},
        ),
    ]
